---
name: Publisher

on:
  release:
    types:
      - released

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to PYPI
    environment: pypi
    steps:
      - name: Checkout ğŸŒ©ï¸
        uses: actions/checkout@v3
      - name: Set up Python ğŸ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Hatch ğŸ¥š
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Build ğŸ”§
        run: hatch build
      - name: Publish ğŸš€
        env:
          HATCH_INDEX_AUTH: ${{ secrets.INDEX_AUTH }}
          HATCH_INDEX_USER: ${{ secrets.INDEX_USER }}
        run: hatch publish
